name: flutter_blue_plus_example
description: Demonstrates how to use the flutter_blue_plus plugin.

publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #ble
  flutter_blue_plus: ^1.4.0

  #map google
  google_maps_flutter: ^2.2.3
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  geolocator: ^9.0.2
  geocoding: ^2.0.3

  #firebase
  cloud_firestore: ^4.4.4
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  firebase_storage: ^11.0.15
  
  #helper
  image_picker: ^0.8.7
  http: ^0.13.5
  flutter_svg: ^2.0.1
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  # adaptive_icon_foreground: "assets/foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

